### Создание пользователя
POST http://localhost:5678/auth/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Михаил",
  "email": "qwe@qwe.qwe",
  "password": "123456",
  "gender": "мужской",
  "birthday": "09.03.1989",
  "userRole": "пользователь",
  "location": "Петроградская",
  "trainingLevel": "любитель",
  "trainingTypes": ["бег", "кроссфит"],
  "questionnaire": {
    "trainingDuration": "30-50 мин",
    "dailyCaloriesCount": 1000,
    "totalCaloriesCount": 5000,
    "isReadyToGetTrained": true
  }
}

### Создание тренера
POST http://localhost:5678/auth/register HTTP/1.1
Content-Type: application/json

{
  "userName": "John",
  "email": "john@qwe.qwe",
  "password": "123456",
  "gender": "мужской",
  "birthday": "01.01.1989",
  "userRole": "тренер",
  "location": "Спортивная",
  "trainingLevel": "профессионал",
  "trainingTypes": ["бег", "кроссфит", "бокс"],
  "questionnaire": {
    "certificates": ["myCoolCertificate.pdf"],
    "description": "The best coach ever",
    "isReadyToTrain": true
  }
}

### Вход
POST http://localhost:5678/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "qwe@qwe.qwe",
  "password": "123456"
}

### Вход
POST http://localhost:5678/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@qwe.qwe",
  "password": "123456"
}

### Выход
GET http://localhost:5678/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDExOWJmZWM0NGRmYjFjYWNmMmNmZDAiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY3ODg3NTY0NiwiZXhwIjoxNjc4ODc2NTQ2fQ.naf-rEZT7yO-6XIleMdQzEHQ5MVQ9Z4ZHtdHSrI8qB4

### Рефреш
GET http://localhost:5678/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDEwYjQzNGJlNjU2NDFmM2E2NmY1NjIiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc4ODE2MzM1LCJleHAiOjE2Nzk0MjExMzV9.vgYgk3drZn15G-nuvtL4XxD7-tZWiHYLODOGrEIJsLk

### Запрос всех пользователей
GET http://localhost:5678/users HTTP/1.1

### Запрос детальной информации о пользователе
GET http://localhost:5678/users/64119f8a4df4601762479d0c HTTP/1.1

### Редактирование информации о пользователе
PATCH http://localhost:5678/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDExOWY4YTRkZjQ2MDE3NjI0NzlkMGMiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY3ODg5ODIxMiwiZXhwIjoxNjc4ODk5MTEyfQ.WCkPldDyoddiKGnNaXMt1Vm-NxIStOEkZk5tyEYv_gA

{
  "userName": "Asdfgh",
  "birthday": "03.01.1988"
}

### Запрос друзей
GET http://localhost:5678/users/friends HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDExOWY4YTRkZjQ2MDE3NjI0NzlkMGMiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY3ODg4MjAyNiwiZXhwIjoxNjc4ODgyOTI2fQ.Op6itGILWfJa5_Un63y33gTlwXKfFvFGy1hXK2zPYBQ

### Добавить в друзья / добавиться в друзья
GET http://localhost:5678/users/friends/add/642b0e23a146a57f8a1f3313 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDcyMjIxMiwiZXhwIjoxNjgwNzIzMTEyfQ.dkMi89DlVO70HSlT9RVLAfiz0T5-7EAx5hXacaPd11M

### Удалить из друзей / удалиться из друзей
GET http://localhost:5678/users/friends/remove/6411e9b3f5722ab2d98bb8ad HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDExOWY4YTRkZjQ2MDE3NjI0NzlkMGMiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiJBc2RmZ2giLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY3ODkwMjk4MiwiZXhwIjoxNjc4OTAzODgyfQ.8HkC-5dhh0Y2_Kp1adWT_fCkFf4vYFBWeJBN4hijgZc

### Загрузка аватара
POST http://localhost:5678/users/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDExOWY4YTRkZjQ2MDE3NjI0NzlkMGMiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiJBc2RmZ2giLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY3ODk2ODA3OSwiZXhwIjoxNjc4OTY4OTc5fQ.GpDDqYZjwqpcLklOp9jCzXNtgwv_sNxyD96CBlWOZ6M

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< /home/mikhail/tmp/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Загрузка сертификата
POST http://localhost:5678/users/certificate HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE5YWJiNmIwOWExMDgxZTk1ZDAyYTAiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc5NDE1NTg0LCJleHAiOjE2Nzk0MTY0ODR9.JhEsL_bef3U209k1HsCDxea97n_L-oxxs7H_KuOSOVs

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="certificate"; filename="certificate.pdf"
Content-Type: application/pdf

< /home/mikhail/tmp/certificate.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--
