version: '3.5'
services:
  mongodb-fitfriends-service:
    image: mongo
    restart: always
    container_name: mongodb-fitfriends-service
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fitfriends-service
    ports:
      - 27019:27017
    volumes:
      - ./db:/data/db

  mongodb-express-fitfriends-service:
    image: mongo-express
    restart: always
    container_name: mongo-express-fitfriends-service
    ports:
      - 8086:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb-fitfriends-service:27017/
