//====================================ТРЕНИРОВКИ========================================
### Создание тренировки
POST http://localhost:5679/trainings HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDc2ODQyOSwiZXhwIjoxNjgwNzY5MzI5fQ._ogjkaa3Kghby_knfB6ic2mmxnDI4sjHxnnj3_SJcTQ

{
  "title": "energy",
  "bgImageUrl": "img/content/thumbnails/training-02.jpg",
  "level": "любитель",
  "type": "стрейчинг",
  "duration": "100 мин — 120 мин",
  "caloriesCount": 5000,
  "description": "Упражнения укрепляют мышечный корсет, делают суставы более гибкими, улучшают осанку и координацию.",
  "gender": "для всех",
  "price": 6500,
  "videoUrl": "videos/0q3874yr-4q3rq3-q34r-erq74.mp4",
  "coachId": "6411af71fba5eba2ef3f7bc0"
}

### Редактирование тренировки
PATCH http://localhost:5679/trainings/641451c413b70ea381cf27f4 HTTP/1.1
Content-Type: application/json

{
  "title": "energy-2",
  "bgImageUrl": "img/content/thumbnails/training-05.jpg",
  "level": "профессионал",
  "duration": "больше 80 мин",
  "caloriesCount": 4500,
  "description": "Будешь прокачан по полной",
  "videoUrl": "videos/0q3874yr-4q3rq3-q34r-QWERTY.mp4"
}

### Запрос всех тренировок (тренер может запросить только свои тренировки)
GET http://localhost:5679/trainings?minPrice=0&maxPrice=4500&minCaloriesCount=0&maxCaloriesCount=2300&duration=30 мин — 50 мин HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE3NGI5NmFlNzQ2ZGI3MmJmODM4YTYiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItGC0YDQtdC90LXRgCIsImlhdCI6MTY3OTM5OTU5MSwiZXhwIjoxNjc5NDAwNDkxfQ.ti_k7UOdcsO5xOOlEqM8w2G2OXzjvkcCq83ElMuy6Rw

### Запрос детальной информации
GET http://localhost:5679/trainings/641451c413b70ea381cf27f4 HTTP/1.1

### Загрузка видео
POST http://localhost:5679/trainings/video/64174be02541b3f1599b4cc2 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE3NGI5NmFlNzQ2ZGI3MmJmODM4YTYiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY3OTMyMDM0MSwiZXhwIjoxNjc5MzIxMjQxfQ.C8kHZH9Yd6C3ckJO6xjbp1-cG4HUL8nmaCOVz2_cd1Q

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="Video_HTML_Academy_1.mp4"
Content-Type: video/mp4

< /home/mikhail/tmp/Video_html_Academy/Video_HTML_Academy_1.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

//====================================ЗАЛЫ========================================

### Создание зала
POST http://localhost:5679/gyms HTTP/1.1
Content-Type: application/json

{
  "title": "Название зала",
  "location": "Петроградская",
  "features": ["бассейн", "бесплатная парковка", "детская комната"],
  "images": ["img/image_01.png", "img/image_02.png"],
  "description": "Описание зала",
  "price": 2500
}

### Список всех залов
GET http://localhost:5679/gyms HTTP/1.1

### Добавить зал в избранное
GET http://localhost:5679/gyms/favorites/add/642b0219b7653404d781dd04 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDU0NjYzOSwiZXhwIjoxNjgwNTQ3NTM5fQ.j0pr3UUYtNw1mSn037SV50ZwpoHhLc84eaeDA-7evDA

### Список избранных залов
GET http://localhost:5679/gyms/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDU0NjYzOSwiZXhwIjoxNjgwNTQ3NTM5fQ.j0pr3UUYtNw1mSn037SV50ZwpoHhLc84eaeDA-7evDA

### Удалить зал из избранных
GET http://localhost:5679/gyms/favorites/remove/642b0219b7653404d781dd04 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDU0NjYzOSwiZXhwIjoxNjgwNTQ3NTM5fQ.j0pr3UUYtNw1mSn037SV50ZwpoHhLc84eaeDA-7evDA

//====================================ЗАКАЗЫ========================================

### Создание заказа
POST http://localhost:5679/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDFhMDY2ZGE4Yjk4NWVlOTgzMjI5MTYiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY3OTQyNzMxMCwiZXhwIjoxNjc5NDI4MjEwfQ.h8xA3Kx4a3a8iExeFHKCV823GrWcMdQiGBrCLFniFug

{
  "orderType": "тренировка",
  "trainingId": "641a06c712c1949fdfbbc8a2",
  "price": 6500,
  "quantity": 1,
  "totalOrderPrice": 6500,
  "paymentMethod": "visa",
  "coachId": "641a065da8b985ee9832290f"
}

### Запрос всех заказов
GET http://localhost:5679/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDFhMDY1ZGE4Yjk4NWVlOTgzMjI5MGYiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc5NDMxMDAxLCJleHAiOjE2Nzk0MzE5MDF9.k45Dm219c6uXk8JVKZtTnIw0HtwkQPX3KTt9PmoVdGQ

### Запрос детальной информации по заказу
GET http://localhost:5679/orders/64189bb68f238f540075037a HTTP/1.1

### Деактивация заказа
GET http://localhost:5679/orders/deactivate/64189bb68f238f540075037a HTTP/1.1

//====================================ОТЗЫВЫ========================================

### Добавление отзыва
POST http://localhost:5679/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDc4MTE0NiwiZXhwIjoxNjgwNzgyMDQ2fQ.35IVpS4P9uwYcrhPuovR0YXXnMauhtw7NrGb7LEA8vY

{
  "trainingId": "642e7dcd0b188e633aa3eab2",
  "userAvatarPath": "img/avatar.png",
  "text": "Текст отзыва qwuytowieyroituwyeoriuytwoeiurytowiueyrotiuweyroiutyweoriuytoweiurytoweiurytsdfgsdfgsdfgsdfgdsfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgsdgfdsgf",
  "rating": 5
}

### Запрос отзывов о тренировке
GET http://localhost:5679/reviews/642e7dcd0b188e633aa3eab2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDc4MTE0NiwiZXhwIjoxNjgwNzgyMDQ2fQ.35IVpS4P9uwYcrhPuovR0YXXnMauhtw7NrGb7LEA8vY
