//====================================ТРЕНИРОВКИ========================================
### Создание тренировки
POST http://localhost:5679/trainings HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU0YzNjMDJjZmI2NzNmODdmOTZhYzciLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiJxd2UiLCJ1c2VyUm9sZSI6ItGC0YDQtdC90LXRgCIsImlhdCI6MTY4MzM5MTY4MiwiZXhwIjoxNjgzMzkyNTgyfQ.l8Adp1YKw5DxkUS2MGec9GxOdxwThYU4sGYlBXzr0-c

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

energy crossfit
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="bgImageUrl"

img/content/thumbnails/training-11.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="level"

любитель
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type"

кроссфит
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="duration"

10-30 мин
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="caloriesCount"

5000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Упражнения укрепляют мышечный корсет, делают суставы более гибкими, улучшают осанку и координацию.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="gender"

для всех
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

6500
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="Video_HTML_Academy_1.mp4"
Content-Type: video/mp4

< /home/mikhail/tmp/Video_html_Academy/Video_HTML_Academy_1.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Редактирование тренировки
PATCH http://localhost:5679/trainings/641451c413b70ea381cf27f4 HTTP/1.1
Content-Type: application/json

{
  "title": "energy-2",
  "bgImageUrl": "img/content/thumbnails/training-05.jpg",
  "level": "профессионал",
  "duration": "больше 80 мин",
  "caloriesCount": 4500,
  "description": "Будешь прокачан по полной",
  "videoUrl": "videos/0q3874yr-4q3rq3-q34r-QWERTY.mp4"
}

### Запрос всех тренировок без параметров
GET http://localhost:5679/trainings HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU0YzNjMDJjZmI2NzNmODdmOTZhYzciLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiJxd2UiLCJ1c2VyUm9sZSI6ItGC0YDQtdC90LXRgCIsImlhdCI6MTY4MzM4NDY4NiwiZXhwIjoxNjgzMzg1NTg2fQ.z8zQZ130u4a54EqEYuh1k5K3srhcS3e4lAYIadtyOTY

### Запрос всех тренировок (тренер может запросить только свои тренировки)
GET http://localhost:5679/trainings?minPrice=0&maxPrice=4500&minCaloriesCount=0&maxCaloriesCount=2300&duration=30 мин — 50 мин HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU0YzNjMDJjZmI2NzNmODdmOTZhYzciLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiJxd2UiLCJ1c2VyUm9sZSI6ItGC0YDQtdC90LXRgCIsImlhdCI6MTY4MzM4NDY4NiwiZXhwIjoxNjgzMzg1NTg2fQ.z8zQZ130u4a54EqEYuh1k5K3srhcS3e4lAYIadtyOTY

### Запрос детальной информации
GET http://localhost:5679/trainings/641451c413b70ea381cf27f4 HTTP/1.1

### Загрузка видео
POST http://localhost:5679/trainings/video/64174be02541b3f1599b4cc2 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE3NGI5NmFlNzQ2ZGI3MmJmODM4YTYiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY3OTMyMDM0MSwiZXhwIjoxNjc5MzIxMjQxfQ.C8kHZH9Yd6C3ckJO6xjbp1-cG4HUL8nmaCOVz2_cd1Q

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="Video_HTML_Academy_1.mp4"
Content-Type: video/mp4

< /home/mikhail/tmp/Video_html_Academy/Video_HTML_Academy_1.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

//====================================ЗАЛЫ========================================

### Список всех залов
GET http://localhost:5679/gyms?minPrice=3000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDM1OTEzMDgzNTg3NWRiMWExYWVhZTUiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MTMyMzQ4NSwiZXhwIjoxNjgxMzI0Mzg1fQ.YvgJTijNySrLWDSS7Be_jr4NvHlcFceWXh6MxjfiYBc

### Добавить зал в избранное
GET http://localhost:5679/gyms/favorites/add/642b0219b7653404d781dd04 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDU0NjYzOSwiZXhwIjoxNjgwNTQ3NTM5fQ.j0pr3UUYtNw1mSn037SV50ZwpoHhLc84eaeDA-7evDA

### Список избранных залов
GET http://localhost:5679/gyms/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDU0NjYzOSwiZXhwIjoxNjgwNTQ3NTM5fQ.j0pr3UUYtNw1mSn037SV50ZwpoHhLc84eaeDA-7evDA

### Удалить зал из избранных
GET http://localhost:5679/gyms/favorites/remove/642b0219b7653404d781dd04 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDU0NjYzOSwiZXhwIjoxNjgwNTQ3NTM5fQ.j0pr3UUYtNw1mSn037SV50ZwpoHhLc84eaeDA-7evDA

//====================================ЗАКАЗЫ========================================

### Создание заказа на тренировку
POST http://localhost:5679/orders/trainings HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDViN2U1ZWQ5ZjRlY2Y3MDJiNDc2NmQiLCJlbWFpbCI6InF3ZTFAcXdlLnF3ZSIsInVzZXJOYW1lIjoi0JzQuNGF0LDQuNC7IiwidXNlclJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2ODM3MTc3MjYsImV4cCI6MTY4MzcxODYyNn0.bI5jCiyRhAxMn6GtocTs1YbRM-JU_Ao8KOLKf61G4s8

{
  "orderType": "тренировка",
  "trainingId": "645685e5c65fdb256f27148e",
  "price": 6504,
  "quantity": 1,
  "totalOrderPrice": 6504,
  "paymentMethod": "umoney",
  "coachId": "6454c3c02cfb673f87f96ac7"
}

### Создание заказа на абонемент в зал
POST http://localhost:5679/orders/gyms HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDViN2U1ZWQ5ZjRlY2Y3MDJiNDc2NmQiLCJlbWFpbCI6InF3ZTFAcXdlLnF3ZSIsInVzZXJOYW1lIjoi0JzQuNGF0LDQuNC7IiwidXNlclJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2ODQwOTEyMTMsImV4cCI6MTY4NDA5MjExM30.d32XJ1MIVef50rm18SkLYfYvXFIslkYalAR4ZM8cAFs

{
  
  "gymId": "6436ac8f5c2d254b7afb7df6",
  "price": 1500,
  "quantity": 1,
  "totalOrderPrice": 1500,
  "paymentMethod": "visa"
}

### Запрос всех заказов на тренировку
GET http://localhost:5679/orders/trainings?sortType=totalSoldQuantity HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDM1OTEyOTgzNTg3NWRiMWExYWVhZGUiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgxNzE3MTg1LCJleHAiOjE2ODE3MTgwODV9.TRVhmGJujDbsxYLohDl4ReAsce-ibmjC8P0BgUDDqq8

### Запрос детальной информации по заказу
GET http://localhost:5679/orders/trainings/64189bb68f238f540075037a HTTP/1.1

### Деактивация заказа
GET http://localhost:5679/orders/deactivate/trainings/64189bb68f238f540075037a HTTP/1.1

//====================================ОТЗЫВЫ========================================

### Добавление отзыва
POST http://localhost:5679/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDc4MTE0NiwiZXhwIjoxNjgwNzgyMDQ2fQ.35IVpS4P9uwYcrhPuovR0YXXnMauhtw7NrGb7LEA8vY

{
  "trainingId": "642e7dcd0b188e633aa3eab2",
  "userAvatarPath": "img/avatar.png",
  "text": "Текст отзыва qwuytowieyroituwyeoriuytwoeiurytowiueyrotiuweyroiutyweoriuytoweiurytoweiurytsdfgsdfgsdfgsdfgdsfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgsdgfdsgf",
  "rating": 5
}

### Запрос отзывов о тренировке
GET http://localhost:5679/reviews/642e7dcd0b188e633aa3eab2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDc4MTE0NiwiZXhwIjoxNjgwNzgyMDQ2fQ.35IVpS4P9uwYcrhPuovR0YXXnMauhtw7NrGb7LEA8vY

//====================================ПОКУПКИ/БАЛАНС========================================

### Покупки пользователя
GET http://localhost:5679/purchases HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDM1OTEzMDgzNTg3NWRiMWExYWVhZTUiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MTMyMzQ4NSwiZXhwIjoxNjgxMzI0Mzg1fQ.YvgJTijNySrLWDSS7Be_jr4NvHlcFceWXh6MxjfiYBc

### Баланс пользователя
GET http://localhost:5679/purchases/balance HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDM1OTEzMDgzNTg3NWRiMWExYWVhZTUiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MTMyMzQ4NSwiZXhwIjoxNjgxMzI0Mzg1fQ.YvgJTijNySrLWDSS7Be_jr4NvHlcFceWXh6MxjfiYBc
