### Создание дневника тренировок
POST http://localhost:5680/trainings-diary HTTP/1.1
Content-Type: application/json

{
  "trainingId": "6411af71fba5eba2ef3f7bc0",
  "trainingTitle": "Energy",
  "userId": "6411af71fba5eba2ef3f7bc0",
  "caloriesCount": 5000,
  "duration": "30-50 мин"
}

### Список тренировок
GET http://localhost:5680/trainings-diary HTTP/1.1
