services:
  mongodb-fitfriends-notifier:
    image: mongo
    restart: always
    container_name: mongodb-fitfriends-notifier
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fitfriends-notifier
    ports:
      - 27021:27017
    volumes:
      - ./db:/data/db

  mongodb-express-fitfriends-notifier:
    image: mongo-express
    restart: always
    container_name: mongo-express-fitfriends-notifier
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb-fitfriends-notifier:27017/
