//===================================ОПОВЕЩЕНИЯ===================================

### Список оповещений
GET http://localhost:5681/notifications HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJiMGUyM2ExNDZhNTdmOGExZjMzMTMiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgwODA2MjY5LCJleHAiOjE2ODA4MDcxNjl9.CVGEIH18sOX17Q6QUa8ssYzeccr-QI2t2W3TpzGCGpM

### Удаление оповещения
DELETE http://localhost:5681/notifications/642ec531fe5d49486d45465c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJiMGUyM2ExNDZhNTdmOGExZjMzMTMiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgwODA0NTM1LCJleHAiOjE2ODA4MDU0MzV9.tOxIdnNFlYtFtPRFuIw6gB72V57d2edrU8PpCCEHskY

//===================================ЗАЯВКИ НА ПЕРСОНАЛЬНУЮ ТРЕНИРОВКУ===================================

### Создание заявки
POST http://localhost:5681/user-requests HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDg4OTc5OSwiZXhwIjoxNjgwODkwNjk5fQ.DT_WtB3PBjf5fZP4gTW_smPID4M0e0k7N-J1xf-bqTU

{
  "type": "fa4fefaw",
  "initiatorId": "3dadw3raw",
  "status": "awefawf"
}
