//===================================ОПОВЕЩЕНИЯ===================================

### Список оповещений
GET http://localhost:5681/notifications HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJiMGUyM2ExNDZhNTdmOGExZjMzMTMiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgwODA2MjY5LCJleHAiOjE2ODA4MDcxNjl9.CVGEIH18sOX17Q6QUa8ssYzeccr-QI2t2W3TpzGCGpM

### Удаление оповещения
DELETE http://localhost:5681/notifications/642ec531fe5d49486d45465c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJiMGUyM2ExNDZhNTdmOGExZjMzMTMiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgwODA0NTM1LCJleHAiOjE2ODA4MDU0MzV9.tOxIdnNFlYtFtPRFuIw6gB72V57d2edrU8PpCCEHskY

//===================================ЗАЯВКИ НА ПЕРСОНАЛЬНУЮ ТРЕНИРОВКУ===================================

### Создание заявки
POST http://localhost:5681/user-requests HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MDk2NTI3NSwiZXhwIjoxNjgwOTY2MTc1fQ.ixyI64MVJpqHfMyGqNI8wNm6Of9pyCoC-LmAi9SQEkQ

{
  "type": "training",
  "userId": "642b0e23a146a57f8a1f3313"
}

### Список заявок
GET http://localhost:5681/user-requests HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJiMGUyM2ExNDZhNTdmOGExZjMzMTMiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgwOTY1NDIxLCJleHAiOjE2ODA5NjYzMjF9.9Wb4QqfBUAPhvUORL3ZlUzHrRkRgF3fiANHwhnQnzP0

### Изменение статуса заявки
PATCH http://localhost:5681/user-requests/64317faeff6fa4eb7c51e767 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJiMGUyM2ExNDZhNTdmOGExZjMzMTMiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgwOTY1NDIxLCJleHAiOjE2ODA5NjYzMjF9.9Wb4QqfBUAPhvUORL3ZlUzHrRkRgF3fiANHwhnQnzP0

{
  "status": "принят"
}

//===================================УВЕДОМЛЕНИЯ===================================

### Запуск рассылки
GET http://localhost:5681/subscription HTTP/1.1

### Подписка/отписка на новые тренировки
GET http://localhost:5681/subscription/643584a8bfe02388190ca66c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIzMDYxMzIyNzM4YWM1NzJiZTEzYzgiLCJlbWFpbCI6InF3ZUBxd2UucXdlIiwidXNlck5hbWUiOiLQnNC40YXQsNC40LsiLCJ1c2VyUm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MTIzMDg3MCwiZXhwIjoxNjgxMjMxNzcwfQ.x2ZjxZQFewKK50Mh3KqHQ_hUgvFzOhsbAIf9qDD_zI8
