### Список оповещений
GET http://localhost:5681/notifications HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJiMGUyM2ExNDZhNTdmOGExZjMzMTMiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgwODA2MjY5LCJleHAiOjE2ODA4MDcxNjl9.CVGEIH18sOX17Q6QUa8ssYzeccr-QI2t2W3TpzGCGpM

### Удаление оповещения
DELETE http://localhost:5681/notifications/642ec531fe5d49486d45465c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJiMGUyM2ExNDZhNTdmOGExZjMzMTMiLCJlbWFpbCI6ImpvaG5AcXdlLnF3ZSIsInVzZXJOYW1lIjoiSm9obiIsInVzZXJSb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjgwODA0NTM1LCJleHAiOjE2ODA4MDU0MzV9.tOxIdnNFlYtFtPRFuIw6gB72V57d2edrU8PpCCEHskY
